name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution snake SVG
        uses: tobiasmeyhoefer/github-contribution-snake-action@v1.0.0
        with:
          username: Athena-Prime-Git
          output: ./output/github-contribution-snake-dark.svg

      - name: Commit and push SVG
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add ./output/github-contribution-snake-dark.svg
          git commit -m "Update contribution snake SVG"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
